# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/constraints.xdc

# Block Designs: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/ip/design_1_lab_0_0/design_1_lab_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lab_0_0 || ORIG_REF_NAME==design_1_lab_0_0} -quiet] -quiet

# IP: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/ip/design_1_lab3_axi_0_0/design_1_lab3_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lab3_axi_0_0 || ORIG_REF_NAME==design_1_lab3_axi_0_0} -quiet] -quiet

# IP: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/hsb2790/Downloads/Lab_3/lab_3/src/design_1_ooc.xdc
